--- #YAML:1.0
name:               Net-Statsd-Server
version:            0.12
abstract:           ~
author:
    - Cosimo Streppone <cosimo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent::Handle::UDP:  0
    IO::Socket::INET:     0
    JSON::XS:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
