---
abstract: "a Perl port of Etsy's statsd *server*"
author:
  - 'Cosimo Streppone <cosimo@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Statsd-Server
requires:
  AnyEvent::Handle::UDP: 0
  IO::Socket::INET: 0
  JSON::XS: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-Statsd-Server
  repository: git://github.com/cosimo/perl5-net-statsd-server.git
version: 0.14
